config/routes.rb
Car::Application.routes.draw do

  get "/sessions/new" => "sessions#new", as: "new_session"
  post "/sessions" => "sessions#create", as: "session"
  delete "/sessions" => "sessions#destroy"

  root 'home#index'

  resources :car_categories

  resources :maintenance_categories

  resources :maintenances

  resources :companies

  resources :autos

  resources :users

  

end

app/models/car_category.rb
class CarCategory < ActiveRecord::Base
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  before_action :set_car_category, only: [:show, :edit, :update, :destroy]

  # GET /car_categories
  # GET /car_categories.json
  def index
    @car_categories = CarCategory.all
  end

  # GET /car_categories/1
  # GET /car_categories/1.json
  def show
  end

  # GET /car_categories/new
  def new
    @car_category = CarCategory.new
  end

  # GET /car_categories/1/edit
  def edit
  end

  # POST /car_categories
  # POST /car_categories.json
  def create
    @car_category = CarCategory.new(car_category_params)

    respond_to do |format|
      if @car_category.save
        format.html { redirect_to @car_category, notice: 'Car category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @car_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_categories/1
  # PATCH/PUT /car_categories/1.json
  def update
    respond_to do |format|
      if @car_category.update(car_category_params)
        format.html { redirect_to @car_category, notice: 'Car category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_categories/1
  # DELETE /car_categories/1.json
  def destroy
    @car_category.destroy
    respond_to do |format|
      format.html { redirect_to car_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_category
      @car_category = CarCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_category_params
      params.require(:car_category).permit(:name)
    end
end

app/helpers/car_categories_helper.rb
module CarCategoriesHelper
end

app/views/car_categories/_form.html.erb
<%= form_for(@car_category) do |f| %>
  <% if @car_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_category.errors.count, "error") %> prohibited this car_category from being saved:</h2>

      <ul>
      <% @car_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/car_categories/edit.html.erb
<h1>Editing car_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @car_category %> |
<%= link_to 'Back', car_categories_path %>

app/views/car_categories/index.html.erb
<h1>Listing car_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @car_categories.each do |car_category| %>
      <tr>
        <td><%= car_category.name %></td>
        <td><%= link_to 'Show', car_category %></td>
        <td><%= link_to 'Edit', edit_car_category_path(car_category) %></td>
        <td><%= link_to 'Destroy', car_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car category', new_car_category_path %>

app/views/car_categories/new.html.erb
<h1>New car_category</h1>

<%= render 'form' %>

<%= link_to 'Back', car_categories_path %>

app/views/car_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car_category.name %>
</p>

<%= link_to 'Edit', edit_car_category_path(@car_category) %> |
<%= link_to 'Back', car_categories_path %>