config/routes.rb
Car::Application.routes.draw do

  get "/sessions/new" => "sessions#new", as: "new_session"
  post "/sessions" => "sessions#create", as: "session"
  delete "/sessions" => "sessions#destroy"

  root 'home#index'

  resources :car_categories

  resources :maintenance_categories

  resources :maintenances

  resources :companies

  resources :autos

  resources :users

  

end

app/models/maintenance_category.rb
class MaintenanceCategory < ActiveRecord::Base
end

app/controllers/maintenance_categories_controller.rb
class MaintenanceCategoriesController < ApplicationController
  before_action :set_maintenance_category, only: [:show, :edit, :update, :destroy]

  # GET /maintenance_categories
  # GET /maintenance_categories.json
  def index
    @maintenance_categories = MaintenanceCategory.all
  end

  # GET /maintenance_categories/1
  # GET /maintenance_categories/1.json
  def show
  end

  # GET /maintenance_categories/new
  def new
    @maintenance_category = MaintenanceCategory.new
  end

  # GET /maintenance_categories/1/edit
  def edit
  end

  # POST /maintenance_categories
  # POST /maintenance_categories.json
  def create
    @maintenance_category = MaintenanceCategory.new(maintenance_category_params)

    respond_to do |format|
      if @maintenance_category.save
        format.html { redirect_to @maintenance_category, notice: 'Maintenance category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @maintenance_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @maintenance_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance_categories/1
  # PATCH/PUT /maintenance_categories/1.json
  def update
    respond_to do |format|
      if @maintenance_category.update(maintenance_category_params)
        format.html { redirect_to @maintenance_category, notice: 'Maintenance category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @maintenance_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_categories/1
  # DELETE /maintenance_categories/1.json
  def destroy
    @maintenance_category.destroy
    respond_to do |format|
      format.html { redirect_to maintenance_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_category
      @maintenance_category = MaintenanceCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maintenance_category_params
      params.require(:maintenance_category).permit(:name)
    end
end

app/helpers/maintenance_categories_helper.rb
module MaintenanceCategoriesHelper
end

app/views/maintenance_categories/_form.html.erb
<%= form_for(@maintenance_category) do |f| %>
  <% if @maintenance_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maintenance_category.errors.count, "error") %> prohibited this maintenance_category from being saved:</h2>

      <ul>
      <% @maintenance_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maintenance_categories/edit.html.erb
<h1>Editing maintenance_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @maintenance_category %> |
<%= link_to 'Back', maintenance_categories_path %>

app/views/maintenance_categories/index.html.erb
<h1>Listing maintenance_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @maintenance_categories.each do |maintenance_category| %>
      <tr>
        <td><%= maintenance_category.name %></td>
        <td><%= link_to 'Show', maintenance_category %></td>
        <td><%= link_to 'Edit', edit_maintenance_category_path(maintenance_category) %></td>
        <td><%= link_to 'Destroy', maintenance_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maintenance category', new_maintenance_category_path %>

app/views/maintenance_categories/new.html.erb
<h1>New maintenance_category</h1>

<%= render 'form' %>

<%= link_to 'Back', maintenance_categories_path %>

app/views/maintenance_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @maintenance_category.name %>
</p>

<%= link_to 'Edit', edit_maintenance_category_path(@maintenance_category) %> |
<%= link_to 'Back', maintenance_categories_path %>